version: "3.6"

services:
  # For development only
  dev:
    depends_on:
      - dev.db
    image: ${DEV_IMAGE}
    env_file:
      - env/cipher.env
      - env/database.env
      - env/secret.env
    working_dir: ${APP_HOME}
    volumes:
      - ../../test:${APP_HOME}
      # for Schematic development only
      - ../build/src:${SCHEMATIC_HOME}
    entrypoint: /bin/sh
    stdin_open: true
    tty: true
